# Generated by Django 4.1.5 on 2023-04-17 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_contact_delete_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phonenumber',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='desc',
            new_name='subject',
        ),
    ]
